# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 05:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('easyaudit', '0003_auto_20170228_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='crudevent',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to=settings.TENANT_MODEL),
        ),
    ]
