# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easyaudit', '0004_crudevent_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crudevent',
            name='object_repr',
            field=models.TextField(blank=True, null=True),
        ),
    ]
